# Generated by Django 2.1.10 on 2019-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_no', models.CharField(help_text='은행 Api 에서 주는 유저의 식별 번호', max_length=10, verbose_name='사용자일련번호')),
                ('connect_info', models.CharField(help_text='은행 Api 에서 주는 유저 연결 정보', max_length=4000, verbose_name='bank_connect_info')),
                ('user_name', models.CharField(help_text='은행 Api 에서 주는 유저 연결 정보', max_length=20, verbose_name='오픈플랫폼고객실명')),
                ('access_token', models.CharField(help_text='은행 Api 사용자 인증용 token', max_length=255, verbose_name='사용자token')),
                ('refresh_token', models.CharField(help_text='은행 Api 사용자 인증용 토큰을 갱신하기 위한 token', max_length=255, verbose_name='사용자갱신용token')),
                ('scope', models.CharField(help_text='은행 Api 에서 주는 유저 연결 정보', max_length=25, verbose_name='오픈플랫폼고객실명')),
                ('expire_time', models.IntegerField(verbose_name='토큰만료시간')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
