# Generated by Django 2.1.10 on 2019-07-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fintech_use_num', models.CharField(max_length=25, verbose_name='핀테크이용번호')),
                ('account_alias', models.CharField(help_text='유저가 회원가입시 기입한 계좌 별명', max_length=50, verbose_name='계좌별명')),
                ('bank_code_std', models.CharField(help_text='3자리 은행 코드', max_length=3, verbose_name='은행표준코드')),
                ('bank_code_sub', models.CharField(help_text='출금/개설 기관 점별 코드', max_length=7, verbose_name='은행점별코드')),
                ('account_num', models.CharField(blank=True, help_text='계좌번호-사업자등록이후사용가능', max_length=20, null=True, verbose_name='계좌번호')),
                ('account_num_masked', models.CharField(help_text='뒷자리가 마스킹된 계좌번호', max_length=20, verbose_name='마스킹된게좌번호')),
                ('account_holder_name', models.CharField(help_text='계좌주의 실명', max_length=20, verbose_name='계좌입금주명')),
                ('account_type', models.CharField(help_text='개인 계좌인지 아닌지 파악용', max_length=1, verbose_name='계좌구분')),
                ('inquiry_agreement', models.CharField(help_text='금융오픈플랫폼(오픈뱅킹) 계좌조회 동의여부', max_length=1, verbose_name='조회서비스동의여부')),
                ('inquiry_agree_datetime', models.DateTimeField(blank=True, null=True, verbose_name='조회서비스동의날짜')),
                ('transfer_agreement', models.CharField(help_text='은행 Api 에서 주는 유저 연결 정보', max_length=25, verbose_name='오픈플랫폼고객실명')),
                ('transfer_agree_datetime', models.DateTimeField(blank=True, null=True, verbose_name='출금서비스동의날짜')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('bank_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_for_bank_user', to='bank.BankUser', verbose_name='은행사용자정보')),
            ],
        ),
    ]
