# Generated by Django 2.1.10 on 2019-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': '은행 유저 정보', 'verbose_name_plural': '은행 유저 정보'},
        ),
        migrations.AlterModelOptions(
            name='bankuser',
            options={'verbose_name': '은행 유저 정보', 'verbose_name_plural': '은행 유저 정보'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='transfer_agreement',
            field=models.CharField(help_text='은행 Api 에서 주는 유저 연결 정보', max_length=25, null=True, verbose_name='오픈플랫폼고객실명'),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='expire_time',
            field=models.DateTimeField(verbose_name='토큰만료시간'),
        ),
        migrations.AlterModelTable(
            name='bankaccount',
            table='bank_account',
        ),
        migrations.AlterModelTable(
            name='bankuser',
            table='bank_user',
        ),
    ]
