# Generated by Django 2.1.11 on 2019-09-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_approved', models.CharField(choices=[('APPROVED', 'APPROVED'), ('UNAPPROVED', 'UNAPPROVED'), ('REJECTED', 'REJECTED')], default='UNAPPROVED', max_length=1)),
            ],
            options={
                'verbose_name': 'Follow Relation',
                'verbose_name_plural': 'Follow Relation 목록',
                'db_table': 'follow_relation',
            },
        ),
        migrations.CreateModel(
            name='UserFollowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('follows', models.ManyToManyField(through='user.FollowRelation', to='user.UserFollowInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Account 목록',
                'db_table': 'user_account',
            },
        ),
        migrations.AddField(
            model_name='followrelation',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.UserFollowInfo'),
        ),
        migrations.AddField(
            model_name='followrelation',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='user.UserFollowInfo'),
        ),
    ]
