# Generated by Django 2.1.11 on 2019-09-18 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_hidden', models.BooleanField(default=False, help_text='숨김처리된 보드는 작성자에게만 노출됩니다.', verbose_name='숨김처리여부')),
                ('title', models.CharField(max_length=255, verbose_name='타이틀')),
                ('content', models.TextField(help_text='마크다운 에디터로 작성되어 마크다운 포맷으로 저장됩니다.', verbose_name='내용')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '카드',
                'verbose_name_plural': '카드 목록',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '카드 Relation',
                'verbose_name_plural': '카드 Relation 목록',
                'db_table': 'card_relation',
            },
        ),
    ]
